#!/usr/bin/env python3

import os
import pyharnessinstruqt

# REQUIRED VARIABLES LIST
HARNESS_ACCOUNT_ID = os.getenv("SE_WORKSHOP_ACCOUNT_ID")
HARNESS_ORG_ID = os.getenv("SE_WORKSHOP_ORG_ID")
HARNESS_PAT = os.getenv("SE_WORKSHOP_PAT")
HARNESS_PROJECT = pyharnessinstruqt.get_agent_variable("HARNESS_PRJ_ID")

# Get manifest for their infra and apply it
pyharnessinstruqt.get_manifest_for_infra(HARNESS_PAT, HARNESS_ACCOUNT_ID, HARNESS_ORG_ID, HARNESS_PROJECT, "lab-hce")
pyharnessinstruqt.run_command("kubectl apply -f lab-hce-harness-chaos-enable.yml")
